### ISSUE TITLE
Subtract

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/timelite#1]
`sub` function to subtract an array of string times.

Example:

```js
sub(['19:30:50', '00:30:10'])
// "19:00:40"
```

**Comment by djschoone** [comment]
How can I help?

**Comment by joseluisq** [comment]
> How can I help?

Hey, here a starting point https://github.com/joseluisq/timelite/blob/master/index.js#L99-L124
Feel free to clone the repo and send some PR.

**Comment by joseluisq** [comment]
@djschoone tell me if you need some help.

**Comment by djschoone** [comment]
@joseluisq I have looked into the different functions. I think the approach is not right. Why not calculate hours, minutes and seconds to an integer in seconds ((hours * 60 * 60) + (minutes * 60) + seconds))? A lot easier to calculate with.

**Comment by joseluisq** [comment]
> @joseluisq I have looked into the different functions. I think the approach is not right. Why not calculate hours, minutes and seconds to an integer in seconds ((hours * 60 * 60) + (minutes * 60) + seconds))? A lot easier to calculate with.

Sure, can you do it?

**Comment by joseluisq** [comment]
It makes more sense work at seconds-integer level. can you suggest an alternative? I open to adopt it.

**Comment by MortenHe** [comment]
any news about the substract method?

**Comment by joseluisq** [comment]
Hey @MortenHe!
The project was frozen but I will resume it in coming weeks.

**Comment by joseluisq** [comment]
If you have ideas please let me know or you can send me a PR.

**Comment by joseluisq** [comment]
[v1.0.0](https://github.com/joseluisq/timelite/releases/tag/v1.0.0) released.
