### ISSUE TITLE
cut off leading zeros

### ISSUE THREAD

**Issue by MortenHe** [joseluisq/timelite#2]
Hi! Thank you for your nice library which works perfectley for my project.

I have a list of video files that a user can add to a playlist. As the videos are shorter than 1 hour the length is always something like 00:mm:ss. For a better display it would be great if the str function had a parameter to optionally cut off those leading zeros. (mm:ss instead of 00:mm:ss).

I think this could be easily done with a check like

if (out.startsWith("00:") {
  return out.substring(3)
}
else {
  return out
}

What do you think?

**Comment by joseluisq** [comment]
Hey! 
Cool that can help you.
Well, I think that timeline should let that feature on the developer side. Because `str` for example, tries to keeping the time ouput values consistent: `HH:mm:ss`

```js
const x = str([0, 2, 5])
// 00:02:05
x.substring(3)
// 02:05
```

If you have more ideas how to improve the library, feel free to send a PR.

**Comment by MortenHe** [comment]
Yes, you're right. Thank for you quick reply and greeting from Germany.
Martin

**Comment by joseluisq** [comment]
You're welcome 👍
