### ISSUE TITLE
Return as string instead of array

### ISSUE THREAD

**Issue by AnwarElbo** [joseluisq/timelite#27]
Is it possible to create a feature to return it as a string to add the extra zeroes. See example to see why. 
Example:
```
let total = add(['01:00', '02:00']);
console.log(total[0] + ':' + total[1]); // Returns 3:0 but I wanna see 03:00.

**Comment by joseluisq** [comment]
If you want the result value as string then just wrap the result with the `str` function.

```ts
let total = add(["01:00", "02:00"])
str(total)
// "03:00:00"
```
